/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package almacen;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ventas.config;

/**
 *
 * @author FIMAZ
 */
public class frmAlmacen extends javax.swing.JFrame {
     Connection conexion;
     DefaultTableModel model; 

    /**
     * Creates new form frmAlmacen
     */
    public frmAlmacen() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
         inicializaBaseDeDatos();
        
        model = new DefaultTableModel();
        tableEntrada.setModel(model);
        
        model.addColumn("producto");
        model.addColumn("precio");
        model.addColumn("cantidad");
        model.addColumn("total");
    }
      public void inicializaBaseDeDatos(){
        try{
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            conexion = DriverManager.
                    getConnection("jdbc:mysql://"
                    + "localhost/punto_venta","root","");
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtProvedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnBuscarProvedor = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEntrada = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Provedor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 22, -1, -1));

        txtProvedor.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        txtProvedor.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtProvedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 19, 104, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 136, -1, -1));

        txtCantidad.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 133, 104, -1));

        btnBuscarProvedor.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        btnBuscarProvedor.setForeground(new java.awt.Color(0, 102, 204));
        btnBuscarProvedor.setText("Buscar Provedor");
        btnBuscarProvedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProvedorActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarProvedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 18, 140, -1));

        btnAgregar.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(0, 102, 204));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 132, -1, -1));

        btnGuardar.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 102, 204));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 132, -1, -1));

        tableEntrada.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tableEntrada.setForeground(new java.awt.Color(51, 51, 51));
        tableEntrada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableEntrada);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 188, 472, 181));

        jButton1.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 204));
        jButton1.setText("Buscar Producto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 77, 140, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Producto");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 81, -1, -1));

        txtProducto.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        txtProducto.setForeground(new java.awt.Color(51, 51, 51));
        txtProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductoActionPerformed(evt);
            }
        });
        getContentPane().add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 78, 104, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/almacen.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 440, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondocafe.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarProvedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProvedorActionPerformed

        frmBuscarProvedor BuscarProveedor= new frmBuscarProvedor(txtProvedor);
        BuscarProveedor.setVisible(true);

    }//GEN-LAST:event_btnBuscarProvedorActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        try{
            PreparedStatement consulta = conexion.prepareStatement(""
                + "SELECT * FROM producto_almacen WHERE status=1 AND id_producto_almacen=?");
            consulta.setString(1, txtProducto.getText());
            ResultSet rs = consulta.executeQuery();

            rs.next();

            Object[] fila = new Object[5];

            fila[0]=txtProducto.getText();
            fila[1]=rs.getString("precio");
            fila[2]=txtCantidad.getText();
            double precio = Double.parseDouble(rs.getString("precio"));
            int cantidad = Integer.parseInt(txtCantidad.getText());
            double total = precio * cantidad;
            fila[3]=""+total;

            model.addRow(fila);
            //limpiar();
            //sumarventa();
        }catch(Exception e){
            e.printStackTrace();
        }                  // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try{
            PreparedStatement consulta = conexion.prepareStatement(""
                + "INSERT INTO almacen_entrada(id_producto, fecha_alta ) VALUES(NOW(),?,?)");

            consulta.setInt(1, config.id_usuario);
            consulta.setString(2, "0");
            consulta.executeUpdate();

            consulta = conexion.prepareStatement("SELECT last_insert_id() as id FROM almacen_entrada");
            ResultSet rs = consulta.executeQuery();
            if (rs.next()){
                int id_venta= rs.getInt("id");
                for(int i=0;i<tableEntrada.getRowCount();i++){

                    int id_producto = Integer.parseInt(tableEntrada.getValueAt(i, 0).toString());
                    int cantidad = Integer.parseInt(tableEntrada.getValueAt(i, 3).toString());
                    double precio= Double.parseDouble(tableEntrada.getValueAt(i, 2).toString());
                    double total= Double.parseDouble(tableEntrada.getValueAt(i, 4).toString());

                    consulta=conexion.prepareStatement(""
                        +"INSERT INTO detalle_venta(id_venta,id_producto,cantidad,precio,total) VALUES (?,?,?,?,?)" );
                    consulta.setInt(1, id_venta);
                    consulta.setInt(2, id_producto);
                    consulta.setInt(3, cantidad);
                    consulta.setDouble(4, precio);
                    consulta.setDouble(5, total);
                    consulta.executeUpdate();

                }
                JOptionPane.showMessageDialog(null, "Venta Realizada");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        frmBuscarProducto BuscarProducto= new frmBuscarProducto(txtProducto);
        BuscarProducto.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAlmacen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarProvedor;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableEntrada;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtProvedor;
    // End of variables declaration//GEN-END:variables
}
