/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package almacen;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego_Alonso
 */
public class frmBuscarProvedor extends javax.swing.JFrame {
Connection conexion;
    JTextField txtIdProveedor;
    /**
     * Creates new form frmBuscarProvedor
     */
    public frmBuscarProvedor() {
        initComponents();
         initComponents();
         setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        inicializaBaseDeDatos();
        llenaTablaProveedor();
    }

     public frmBuscarProvedor(JTextField txtIdProveedor) {
        initComponents();
        inicializaBaseDeDatos();
        llenaTablaProveedor();
        this.txtIdProveedor=txtIdProveedor;
    }
    
    public void inicializaBaseDeDatos(){
        try{
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            conexion = DriverManager.
                    getConnection("jdbc:mysql://"
                    + "localhost/punto_venta","root","");
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
        
    public void llenaTablaProveedor(){
        try{            
            DefaultTableModel model = new DefaultTableModel();
            tableBuscarProvedor.setModel(model);
            
            PreparedStatement consulta = conexion.prepareStatement(""
                    + "SELECT id_provedor, nombre "
                    + " FROM provedores WHERE status=1");                  
            ResultSet rs = consulta.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();            
            for(int i = 1; i <= cantidadColumnas; i++){
                model.addColumn(rsMd.getColumnLabel(i));
            }
            
            
            while(rs.next()){
                Object[] fila = new Object[cantidadColumnas];
                for(int j=1; j <= cantidadColumnas; j++){
                    fila[j-1] = rs.getObject(j);
                }                
                
                model.addRow(fila);
            }
            
            
        }catch(Exception e){
            e.printStackTrace();
                    
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableBuscarProvedor = new javax.swing.JTable();
        txtBuscaProvedor = new javax.swing.JTextField();
        btnSeleccionar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableBuscarProvedor.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tableBuscarProvedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableBuscarProvedor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 232));

        txtBuscaProvedor.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        txtBuscaProvedor.setForeground(new java.awt.Color(0, 102, 153));
        txtBuscaProvedor.setText("              Provedores");
        txtBuscaProvedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaProvedorActionPerformed(evt);
            }
        });
        txtBuscaProvedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaProvedorKeyReleased(evt);
            }
        });
        getContentPane().add(txtBuscaProvedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 181, -1));

        btnSeleccionar.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        btnSeleccionar.setForeground(new java.awt.Color(0, 102, 153));
        btnSeleccionar.setText("Seleccionar Provedor");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscaProvedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaProvedorKeyReleased
        try{
            DefaultTableModel model = new DefaultTableModel();
            tableBuscarProvedor.setModel(model);

            /*
            PreparedStatement consulta = conexion.prepareStatement(""
                + "SELECT * FROM usuarios WHERE status=1 AND nombre LIKE ?");
            consulta.setString( 1, "%"+txtBuscar.getText()+"%");
            */
            PreparedStatement consulta = conexion.prepareStatement(""
                + "SELECT id_producto, descripcion FROM producto WHERE status=1 AND nombre LIKE ?");
            consulta.setString( 1,"'"+txtBuscaProvedor.getText()+"'");
            ResultSet rs = consulta.executeQuery();

            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
            for(int i = 1; i <= cantidadColumnas; i++){
                model.addColumn(rsMd.getColumnLabel(i));
            }

            while(rs.next()){
                Object[] fila = new Object[cantidadColumnas];
                for(int j=1; j <= cantidadColumnas; j++){
                    fila[j-1] = rs.getObject(j);
                }

                model.addRow(fila);
            }

        }catch(Exception e){
            e.printStackTrace();

        }             // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaProvedorKeyReleased

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        int id = (int) tableBuscarProvedor.getValueAt(tableBuscarProvedor.getSelectedRow() , 0);
        txtIdProveedor.setText(""+id);
        this.dispose();
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void txtBuscaProvedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaProvedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaProvedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBuscarProvedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBuscarProvedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBuscarProvedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBuscarProvedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBuscarProvedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableBuscarProvedor;
    private javax.swing.JTextField txtBuscaProvedor;
    // End of variables declaration//GEN-END:variables
}
