/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package almacen;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego_Alonso
 */
public class frmProductosEntrada extends javax.swing.JFrame {
     private Connection conexion;
    boolean modificando=false;

    /**
     * Creates new form frmProductosEntrada
     */
    public frmProductosEntrada() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        inicializaBaseDeDatos();
        llenarTablaProductosAlmacen();
    }
    public void inicializaBaseDeDatos(){
        try{
        DriverManager.registerDriver(new com.mysql.jdbc.Driver()); // para cargar el driver en java
        conexion=DriverManager.getConnection("jdbc:mysql://" + "localhost/punto_venta","root","");// PARA CONECTARNOS CON LA BASE DE DATOS
        }catch (Exception ex){
            ex.printStackTrace();
        }
        
    }
    public void llenarTablaProductosAlmacen(){
        try{
            DefaultTableModel model= new DefaultTableModel();
            tableProductos.setModel(model);
            PreparedStatement consulta = conexion.prepareStatement("" + "SELECT * FROM producto_almacen Where status=1");
            ResultSet rs= consulta.executeQuery();
            ResultSetMetaData rsMd =rs.getMetaData();
            int cantidadColumnas=rsMd.getColumnCount();
            for (int i=1; i<=cantidadColumnas; i ++){
                model.addColumn(rsMd.getColumnLabel(i));
                
            }
            while(rs.next()){
                Object[] fila = new Object[cantidadColumnas];
                for (int j=1; j <= cantidadColumnas; j++){
                    fila[j-1]= rs.getObject(j);
                }
                model.addRow(fila);
                }
            }catch (Exception e){
                e.printStackTrace();
                
            }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProductos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID Producto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txtIdProducto.setEditable(false);
        txtIdProducto.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        txtIdProducto.setForeground(new java.awt.Color(51, 51, 51));
        txtIdProducto.setText("       Nuevo");
        getContentPane().add(txtIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 110, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        txtNombre.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(51, 51, 51));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 110, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Precio");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        txtPrecio.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 110, -1));

        btnGuardar.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 51, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        btnModificar.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(0, 51, 255));
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 51, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));

        tableProductos.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tableProductos.setForeground(new java.awt.Color(51, 51, 51));
        tableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableProductos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 222, 580, 120));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registro de Producto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondoralla.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 610, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String Nombre = txtNombre.getText();
        String precio=txtPrecio.getText();

        int id=0;
        if(modificando){
            id=Integer.parseInt(txtIdProducto.getText());
        }
        if(Nombre.length()== 0 || precio.length()== 0)
        {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos para registrar");
            return;
        }
        try{
            PreparedStatement consulta;
            if(modificando){
                consulta=conexion.prepareStatement("" + "UPDATE producto_almacen SET nombre=?,precio=? WHERE id_producto_almacen=?" );
                consulta.setString(1, Nombre);
                consulta.setString(2, precio);
                consulta.setInt(3, id);
            }else{
                consulta=conexion.prepareStatement(""+"INSERT INTO producto_almacen (nombre, precio)VALUES(?,?)");
                consulta.setString(1, Nombre);
                consulta.setString(2, precio);
                
            }
            consulta.executeUpdate();

            llenarTablaProductosAlmacen();
            limpiar();
            btnGuardar.setText("Guardar");

        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        }
        public void limpiar(){
            txtNombre.setText("");
            txtPrecio.setText("");
            modificando=false;
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int id = (int) tableProductos.getValueAt(tableProductos.getSelectedRow(), 0);
        String nombre =(String)tableProductos.getValueAt(tableProductos.getSelectedRow(), 1);
        String precio =(String)tableProductos.getValueAt(tableProductos.getSelectedRow(), 2);

        txtIdProducto.setText("" + id);
        txtNombre.setText(nombre);
        txtPrecio.setText(precio);
        btnGuardar.setText("Actualizar");
        modificando=true;
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int id =(int)tableProductos.getValueAt(tableProductos.getSelectedRow(), 0); //seleccionar el campo seleccionado de la tabla

        try{

            PreparedStatement consulta=conexion.prepareStatement(""+"UPDATE  producto_almacen SET status=2 WHERE id_producto_almacen=?");

            consulta.setInt(1, id);
            consulta.executeUpdate();
            llenarTablaProductosAlmacen();
            limpiar();
            txtIdProducto.setText("  Nuevo");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProductosEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProductosEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProductosEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProductosEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProductosEntrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableProductos;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
