/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ventas;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ventas.frmBuscarProducto;

/**
 *
 * @author Diego_Alonso
 */
public class frmventa extends javax.swing.JFrame {
    
     Connection conexion;
     DefaultTableModel model;   // cuales son los campos a mostrar
    /**
     * Creates new form frmventa
     */
    public frmventa() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
       
        inicializaBaseDeDatos();
        
        model = new DefaultTableModel();
        tableVenta.setModel(model);
        
        model.addColumn("id_producto");
        model.addColumn("descripcion");
        model.addColumn("precio");
        model.addColumn("cantidad");
        model.addColumn("total");       
    }
    
     public void inicializaBaseDeDatos(){
        try{
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            conexion = DriverManager.
                    getConnection("jdbc:mysql://"
                    + "localhost/punto_venta","root","");
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableVenta = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        txtProducto = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        total = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableVenta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 440, 200));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 104, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Producto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 59, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Folio");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 14, -1, -1));
        getContentPane().add(txtIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 11, 77, -1));
        getContentPane().add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 56, 77, -1));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 101, 77, -1));

        btnBuscar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 102, 204));
        btnBuscar.setText("Buscar Producto");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 55, -1, -1));

        btnGuardar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 102, 204));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 150, -1, -1));

        btnAgregar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(0, 102, 204));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 150, -1, -1));

        total.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));
        total.setText("Total");
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 154, -1, -1));

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 151, 77, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/registrdoraa.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondoralla.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    
    frmBuscarProducto frmBuscar= new frmBuscarProducto(txtProducto);
        frmBuscar.setVisible(true);
    
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
 
                       try{
            PreparedStatement consulta = conexion.prepareStatement(""
                    + "SELECT * FROM producto WHERE status=1 AND id_producto=?");
            consulta.setString(1, txtProducto.getText());
            ResultSet rs = consulta.executeQuery();            
            
            rs.next();

            Object[] fila = new Object[5];

            fila[0]=txtProducto.getText();
            fila[1]=rs.getString("descripcion");
            fila[2]=rs.getString("precio");
            fila[3]=txtCantidad.getText();
            double precio = Double.parseDouble(rs.getString("precio"));
            int cantidad = Integer.parseInt(txtCantidad.getText());
            double total = precio * cantidad;
            fila[4]=""+total;

            model.addRow(fila);        
            limpiar();
            sumarventa();
        }catch(Exception e){
            e.printStackTrace();
        }                  // TODO add your handling code here:                    
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try{
         PreparedStatement consulta = conexion.prepareStatement(""
                    + "INSERT INTO ventas(fecha_venta, id_usuario, total) VALUES(NOW(),?,?)");
         
       
            consulta.setInt(1, config.id_usuario);
            consulta.setString(2, "0");
            consulta.executeUpdate();  
         
        
            consulta = conexion.prepareStatement("SELECT last_insert_id() as id FROM ventas");
           ResultSet rs = consulta.executeQuery();    
            if (rs.next()){
            int id_venta= rs.getInt("id");
            for(int i=0;i<tableVenta.getRowCount();i++){ 
             
                  int id_producto= Integer.parseInt(tableVenta.getValueAt(i, 0).toString());
                  int cantidad= Integer.parseInt(tableVenta.getValueAt(i, 3).toString());
                  double precio= Double.parseDouble(tableVenta.getValueAt(i, 2).toString());
                  double total= Double.parseDouble(tableVenta.getValueAt(i, 4).toString());
                  
                  consulta=conexion.prepareStatement(""
                          +"INSERT INTO detalle_venta(id_venta,id_producto,cantidad,precio,total) VALUES (?,?,?,?,?)" );
               consulta.setInt(1, id_venta);
               consulta.setInt(2, id_producto);
               consulta.setInt(3, cantidad);
               consulta.setDouble(4, precio);
               consulta.setDouble(5, total);
               consulta.executeUpdate(); 
                    
                  
            }
              JOptionPane.showMessageDialog(null, "Venta Realizada");
            }
    }catch(Exception e){
         e.printStackTrace();
        }  
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

     public void sumarventa(){
        double suma=0;
        for(int i=0;i<tableVenta.getRowCount();i++){
            suma+=Double.parseDouble(tableVenta.getValueAt(i, 4).toString());
            
        }
        txtTotal.setText(""+suma);
    }
       public void limpiar(){
        txtProducto.setText("");
        txtCantidad.setText("");
       
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmventa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmventa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmventa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmventa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmventa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableVenta;
    private javax.swing.JLabel total;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
