/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package provedores;

import almacen.frmBuscarProvedor;
import almacen.frmProductosEntrada;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FIMAZ
 */
public class frmprovedor extends javax.swing.JFrame {
    private Connection conexion;
    boolean modificando=false;

    /**
     * Creates new form frmprovedor
     */
    public frmprovedor() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        inicializaBaseDeDatos();
        llenarTablaUsuarios();
    }
    public void inicializaBaseDeDatos(){
        try{
        DriverManager.registerDriver(new com.mysql.jdbc.Driver()); // para cargar el driver en java
        conexion=DriverManager.getConnection("jdbc:mysql://" + "localhost/punto_venta","root","");// PARA CONECTARNOS CON LA BASE DE DATOS
        }catch (Exception ex){
            ex.printStackTrace();
        }
        
    }
    public void llenarTablaUsuarios(){
        try{
            DefaultTableModel model= new DefaultTableModel();
            tableProvedor.setModel(model);
            PreparedStatement consulta = conexion.prepareStatement("" + "SELECT * FROM provedores Where status=1");
            ResultSet rs= consulta.executeQuery();
            ResultSetMetaData rsMd =rs.getMetaData();
            int cantidadColumnas=rsMd.getColumnCount();
            for (int i=1; i<=cantidadColumnas; i ++){
                model.addColumn(rsMd.getColumnLabel(i));
                
            }
            while(rs.next()){
                Object[] fila = new Object[cantidadColumnas];
                for (int j=1; j <= cantidadColumnas; j++){
                    fila[j-1]= rs.getObject(j);
                }
                model.addRow(fila);
                }
            }catch (Exception e){
                e.printStackTrace();
                
            }
    
            }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProvedor = new javax.swing.JTable();
        txtEmail = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAMaterno = new javax.swing.JTextField();
        txtAPaterno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtIdProvedor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableProvedor.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tableProvedor.setForeground(new java.awt.Color(51, 51, 51));
        tableProvedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableProvedor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 580, 120));

        txtEmail.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 110, -1));

        txtTelefono.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 110, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefono");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellido Materno");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        txtAMaterno.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        txtAMaterno.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtAMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 110, -1));

        txtAPaterno.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        txtAPaterno.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtAPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 110, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido Paterno");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        txtNombre.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(51, 51, 51));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 110, -1));

        txtIdProvedor.setEditable(false);
        txtIdProvedor.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        txtIdProvedor.setForeground(new java.awt.Color(51, 51, 51));
        txtIdProvedor.setText("       Nuevo");
        getContentPane().add(txtIdProvedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 110, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID Provedor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        btnGuardar.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 102, 204));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        btnModificar.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(0, 102, 204));
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 102, 204));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Empresa");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        txtEmpresa.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        txtEmpresa.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 110, -1));

        jButton1.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 204));
        jButton1.setText("Ingresar Productos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Registro de Proveedores");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/provedoress.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 260, 250));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondoralla.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String Nombre = txtNombre.getText();
        String a_paterno=txtAPaterno.getText();
        String a_materno=txtAMaterno.getText();
        String email=txtEmail.getText();
        String empresa=txtEmpresa.getText();
        String telefono=txtTelefono.getText();
        
        int id=0;
        if(modificando){
            id=Integer.parseInt(txtIdProvedor.getText());
        }
        if(Nombre.length()== 0 || a_paterno.length()== 0||a_materno.length()==0||email.length()==0 ||empresa.length()==0 ||telefono.length()==0)
        {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos para registrar");
            return;
        }
        try{
            PreparedStatement consulta;
            if(modificando){
                consulta=conexion.prepareStatement("" + "UPDATE provedores SET nombre=?,a_paterno=?,a_materno=?,email=?,empresa=?,telefono=? WHERE id_provedor=?" );
                consulta.setString(1, Nombre);
                consulta.setString(2, a_paterno);
                consulta.setString(3, a_materno);
                consulta.setString(4, email);
                consulta.setString(5, empresa);
                consulta.setString(6, telefono);
                consulta.setInt(7, id);
            }else{
                consulta=conexion.prepareStatement(""+"INSERT INTO provedores (nombre, a_paterno,a_materno,email,empresa,telefono)VALUES(?,?,?,?,?,?)");
                consulta.setString(1, Nombre);
                consulta.setString(2, a_paterno);
                consulta.setString(3, a_materno);
                consulta.setString(4, email);
                consulta.setString(5, empresa);
                consulta.setString(6, telefono);
            }
            consulta.executeUpdate();

            llenarTablaUsuarios();
            limpiar();
            btnGuardar.setText("Guardar");

        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        }
        public void limpiar(){
            txtNombre.setText("");
            txtAPaterno.setText("");
            txtAMaterno.setText("");
            txtTelefono.setText("");
            txtEmail.setText("");
            txtEmpresa.setText("");
            modificando=false;
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int id = (int) tableProvedor.getValueAt(tableProvedor.getSelectedRow(), 0);
        String nombre =(String)tableProvedor.getValueAt(tableProvedor.getSelectedRow(), 1);
        String a_paterno =(String)tableProvedor.getValueAt(tableProvedor.getSelectedRow(), 2);
        String a_materno =(String)tableProvedor.getValueAt(tableProvedor.getSelectedRow(), 3);
        String email =(String)tableProvedor.getValueAt(tableProvedor.getSelectedRow(), 4);
        String empresa =(String)tableProvedor.getValueAt(tableProvedor.getSelectedRow(), 5);
        String telefono =(String)tableProvedor.getValueAt(tableProvedor.getSelectedRow(), 6);
        

        txtIdProvedor.setText("" + id);
        txtNombre.setText(nombre);
        txtAPaterno.setText(a_paterno);
        txtAMaterno.setText(a_materno);
        txtTelefono.setText(telefono);
        txtEmail.setText(email);
        txtEmpresa.setText(empresa);
        btnGuardar.setText("Actualizar");
        modificando=true;

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int id =(int)tableProvedor.getValueAt(tableProvedor.getSelectedRow(), 0); //seleccionar el campo seleccionado de la tabla

        try{

            PreparedStatement consulta=conexion.prepareStatement(""+"UPDATE  provedores SET status=2 WHERE id_provedor=?");

            consulta.setInt(1, id);
            consulta.executeUpdate();
            llenarTablaUsuarios();
            limpiar();
            txtIdProvedor.setText("  Nuevo");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         frmProductosEntrada productoEntrada= new frmProductosEntrada();
        productoEntrada.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmprovedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmprovedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmprovedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmprovedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmprovedor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableProvedor;
    private javax.swing.JTextField txtAMaterno;
    private javax.swing.JTextField txtAPaterno;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtIdProvedor;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
