/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package usuarios;

import com.sun.jmx.snmp.BerDecoder;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author corona
 */
public class frmCliente extends javax.swing.JFrame {
    private Connection conexion;
    boolean modificando=false;

    /**
     * Creates new form frmCliente
     */
    public frmCliente() {
        initComponents();
        inicializaBaseDeDatos();
        llenarTablaUsuarios();
    }
    public void inicializaBaseDeDatos(){
        try{
        DriverManager.registerDriver(new com.mysql.jdbc.Driver()); // para cargar el driver en java
        conexion=DriverManager.getConnection("jdbc:mysql://" + "localhost/punto_venta","root","");// PARA CONECTARNOS CON LA BASE DE DATOS
        }catch (Exception ex){
            ex.printStackTrace();
        }
        
    }
public void llenarTablaUsuarios(){
        try{
            DefaultTableModel model= new DefaultTableModel();
            tableCliente.setModel(model);
            PreparedStatement consulta = conexion.prepareStatement("" + "SELECT * FROM clientes Where status=1");
            ResultSet rs= consulta.executeQuery();
            ResultSetMetaData rsMd =rs.getMetaData();
            int cantidadColumnas=rsMd.getColumnCount();
            for (int i=1; i<=cantidadColumnas; i ++){
                model.addColumn(rsMd.getColumnLabel(i));
                
            }
            while(rs.next()){
                Object[] fila = new Object[cantidadColumnas];
                for (int j=1; j <= cantidadColumnas; j++){
                    fila[j-1]= rs.getObject(j);
                }
                model.addRow(fila);
                }
            }catch (Exception e){
                e.printStackTrace();
                
            }
    
            }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtAPaterno = new javax.swing.JTextField();
        txtAMaterno = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCliente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Apellido Paterno");

        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Apellido Materno");

        jLabel5.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Telefono");

        jLabel6.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Email");

        txtNombre.setForeground(new java.awt.Color(0, 0, 255));

        txtAPaterno.setForeground(new java.awt.Color(0, 0, 255));

        txtAMaterno.setForeground(new java.awt.Color(0, 0, 255));

        txtTelefono.setForeground(new java.awt.Color(0, 0, 255));

        txtEmail.setForeground(new java.awt.Color(0, 0, 255));

        btnGuardar.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 204));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        tableCliente.setForeground(new java.awt.Color(0, 0, 255));
        tableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableCliente);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("ID cliente");

        txtIdCliente.setEditable(false);
        txtIdCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtIdCliente.setForeground(new java.awt.Color(204, 0, 0));
        txtIdCliente.setText("       Nuevo");

        btnModificar.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(0, 0, 204));
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 204));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtIdCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnModificar)
                            .addComponent(btnEliminar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String Nombre = txtNombre.getText();
        String apellido_paterno=txtAPaterno.getText();
        String apellido_materno=txtAMaterno.getText();
        String telefono=txtTelefono.getText();
        String email=txtEmail.getText();
        int id=0;
        if(modificando){
            id=Integer.parseInt(txtIdCliente.getText());
        }
        if(Nombre.length()== 0 || apellido_paterno.length()== 0||apellido_materno.length()==0||telefono.length()==0 ||email.length()==0)
        {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos para registrar");
            return;
        }        
        try{
            PreparedStatement consulta;
            if(modificando){
                consulta=conexion.prepareStatement("" + "UPDATE clientes SET nombre=?,apellido_paterno=?,apellido_materno=?,telefono=?,email=? WHERE id_clientes=?" );
                consulta.setString(1, Nombre);
                consulta.setString(2, apellido_paterno);
                consulta.setString(3, apellido_materno);
                consulta.setString(4, telefono);
                consulta.setString(5, email);
                consulta.setInt(6, id);
            }else{
            consulta=conexion.prepareStatement(""+"INSERT INTO clientes (nombre, apellido_paterno,apellido_materno,telefono,email)VALUES(?,?,?,?,?)");
            consulta.setString(1, Nombre);
            consulta.setString(2, apellido_paterno);
            consulta.setString(3, apellido_materno);
            consulta.setString(4, telefono);
            consulta.setString(5, email);
            }
            consulta.executeUpdate();
            
            llenarTablaUsuarios();
            limpiar();
            btnGuardar.setText("Guardar");
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
    }                                          
public void limpiar(){
    txtNombre.setText("");
    txtAPaterno.setText("");
    txtAMaterno.setText("");
    txtTelefono.setText("");
    txtEmail.setText("");
    modificando=false;
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
          int id =(int)tableCliente.getValueAt(tableCliente.getSelectedRow(), 0); //seleccionar el campo seleccionado de la tabla
       
         try{
             
            PreparedStatement consulta=conexion.prepareStatement(""+"UPDATE  clientes SET status=2 WHERE id_clientes=?");
            
            consulta.setInt(1, id);
            consulta.executeUpdate();
            llenarTablaUsuarios();
            limpiar();
            txtIdCliente.setText("  Nuevo");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int id = (int) tableCliente.getValueAt(tableCliente.getSelectedRow(), 0);
        String nombre =(String)tableCliente.getValueAt(tableCliente.getSelectedRow(), 1);
        String apellido_paterno =(String)tableCliente.getValueAt(tableCliente.getSelectedRow(), 2);
        String apellido_materno =(String)tableCliente.getValueAt(tableCliente.getSelectedRow(), 3);
        String telefono =(String)tableCliente.getValueAt(tableCliente.getSelectedRow(), 4);
        String email =(String)tableCliente.getValueAt(tableCliente.getSelectedRow(), 5);
       
        
    txtIdCliente.setText("" + id);
    txtNombre.setText(nombre);
    txtAPaterno.setText(apellido_paterno);
    txtAMaterno.setText(apellido_materno);
    txtTelefono.setText(telefono);
    txtEmail.setText(email);
    btnGuardar.setText("Actualizar");
    modificando=true;
   
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCliente;
    private javax.swing.JTextField txtAMaterno;
    private javax.swing.JTextField txtAPaterno;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
