/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package usuarios;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


    /**
 *
 * @author FIMAZ
 */
public class frmCatalogoUsuario extends javax.swing.JFrame {
    private Connection conexion;
    boolean modificando=false;

    /**
     * Creates new form frmCatalogoUsuario
     */
    public frmCatalogoUsuario() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        inicializaBaseDeDatos();
        llenarTablaUsuarios();
        
    }
    public void inicializaBaseDeDatos(){
        try{
        DriverManager.registerDriver(new com.mysql.jdbc.Driver()); // para cargar el driver en java
        conexion=DriverManager.getConnection("jdbc:mysql://" + "localhost/punto_venta","root","");// PARA CONECTARNOS CON LA BASE DE DATOS
        }catch (Exception ex){
            ex.printStackTrace();
        }
        
    }
    public void llenarTablaUsuarios(){
        try{
            DefaultTableModel model= new DefaultTableModel();
            tableUsuario.setModel(model);
            PreparedStatement consulta = conexion.prepareStatement("" + "SELECT * FROM usuarios Where status=1");
            ResultSet rs= consulta.executeQuery();
            ResultSetMetaData rsMd =rs.getMetaData();
            int cantidadColumnas=rsMd.getColumnCount();
            for (int i=1; i<=cantidadColumnas; i ++){
                model.addColumn(rsMd.getColumnLabel(i));
                
            }
            while(rs.next()){
                Object[] fila = new Object[cantidadColumnas];
                for (int j=1; j <= cantidadColumnas; j++){
                    fila[j-1]= rs.getObject(j);
                }
                model.addRow(fila);
                }
            }catch (Exception e){
                e.printStackTrace();
                
            }
    
            }
    
/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUsuario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtUcuario = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        btneliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel12.setText("jLabel12");

        jLabel13.setText("jLabel13");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableUsuario.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableUsuario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 730, 110));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido Paterno");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido Materno");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Usuario");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contraseña");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        txtNombre.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(51, 51, 51));
        txtNombre.setPreferredSize(new java.awt.Dimension(80, 25));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 170, -1));

        txtApellidoP.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        txtApellidoP.setForeground(new java.awt.Color(51, 51, 51));
        txtApellidoP.setPreferredSize(new java.awt.Dimension(80, 25));
        getContentPane().add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 170, -1));

        txtApellidoM.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        txtApellidoM.setForeground(new java.awt.Color(51, 51, 51));
        txtApellidoM.setPreferredSize(new java.awt.Dimension(80, 25));
        getContentPane().add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 170, -1));

        txtEmail.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(51, 51, 51));
        txtEmail.setPreferredSize(new java.awt.Dimension(80, 25));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 170, -1));

        txtUcuario.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        txtUcuario.setForeground(new java.awt.Color(51, 51, 51));
        txtUcuario.setPreferredSize(new java.awt.Dimension(80, 25));
        getContentPane().add(txtUcuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 170, -1));

        btnGuardar.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 51, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 93, -1));

        txtPassword.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(51, 51, 51));
        txtPassword.setPreferredSize(new java.awt.Dimension(80, 25));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 170, -1));

        btneliminar.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(0, 51, 255));
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 83, -1));

        btnModificar.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(0, 51, 255));
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        txtid.setEditable(false);
        txtid.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        txtid.setForeground(new java.awt.Color(51, 51, 51));
        txtid.setText("                Nuevo");
        txtid.setPreferredSize(new java.awt.Dimension(80, 25));
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 170, -1));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Buscar");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));

        txtBuscar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(51, 51, 51));
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 170, -1));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Registro de Usuarios");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/usuarioss.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 250, 260));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondoralla.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String Nombre = txtNombre.getText();
        String apellido_paterno=txtApellidoP.getText();
        String apellido_materno=txtApellidoM.getText();
        String email=txtEmail.getText();
        String usuario=txtUcuario.getText();
        String password=txtPassword.getText();
        int id=0;
        if(modificando){
            id=Integer.parseInt(txtid.getText());
        }
        if(Nombre.length()== 0 || apellido_paterno.length()== 0||apellido_materno.length()==0||email.length()==0 ||usuario.length()==0||password.length()==0)
        {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos para registrar");
            return;
        }        
        try{
            PreparedStatement consulta;
            if(modificando){
            consulta=conexion.prepareStatement(""+"UPDATE  usuarios SET nombre=?,apellido_paterno=?,apellido_materno=?,email=?,usuario=?,contrasena=? WHERE id_usuario=?");
            consulta.setString(1, Nombre);
            consulta.setString(2, apellido_paterno);
            consulta.setString(3, apellido_materno);
            consulta.setString(4, email);
            consulta.setString(5, usuario);
            consulta.setString(6, password);
            consulta.setInt(7,id);
            }else{
            consulta=conexion.prepareStatement(""+"INSERT INTO usuarios (nombre, apellido_paterno,apellido_materno,email,usuario,contrasena)VALUES(?,?,?,?,?,?)");
            consulta.setString(1, Nombre);
            consulta.setString(2, apellido_paterno);
            consulta.setString(3, apellido_materno);
            consulta.setString(4, email);
            consulta.setString(5, usuario);
            consulta.setString(6, password);
            }
            
            consulta.executeUpdate();
            
            llenarTablaUsuarios();
            limpiar();
            btnGuardar.setText("Guardar");
            txtid.setText("   Nuevo");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // boton eliminar, dar baja logica status
        int id =(int)tableUsuario.getValueAt(tableUsuario.getSelectedRow(), 0); //seleccionar el campo seleccionado de la tabla
       
         try{
             
            PreparedStatement consulta=conexion.prepareStatement(""+"UPDATE  usuarios SET status=2 WHERE id_usuario=?");
            
            consulta.setInt(1, id);
            consulta.executeUpdate();
            llenarTablaUsuarios();
            limpiar();
            txtid.setText("   Nuevo");
                    
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
             
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // boton modificar
        int id = (int) tableUsuario.getValueAt(tableUsuario.getSelectedRow(), 0);
        String nombre =(String)tableUsuario.getValueAt(tableUsuario.getSelectedRow(), 1);
        String apellido_paterno =(String)tableUsuario.getValueAt(tableUsuario.getSelectedRow(), 2);
        String apellido_materno =(String)tableUsuario.getValueAt(tableUsuario.getSelectedRow(), 3);
        String email =(String)tableUsuario.getValueAt(tableUsuario.getSelectedRow(), 4);
        String usuario =(String)tableUsuario.getValueAt(tableUsuario.getSelectedRow(), 5);
        String password=(String)tableUsuario.getValueAt(tableUsuario.getSelectedRow(), 6);
        
    txtid.setText("" + id);
    txtNombre.setText(nombre);
    txtApellidoP.setText(apellido_paterno);
    txtApellidoM.setText(apellido_materno);
    txtEmail.setText(email);
    txtUcuario.setText(usuario);
    txtPassword.setText(password);
    btnGuardar.setText("Actualizar");
    modificando=true;
    
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        try{
        DefaultTableModel model= new DefaultTableModel();
        tableUsuario.setModel(model);
        PreparedStatement consulta=conexion.prepareStatement("" + "SELECT * FROM usuarios Where status=1 AND  nombre LIKE ?");
        consulta.setString(1,"%" + txtBuscar.getText() +"%");
        ResultSet rs= consulta.executeQuery();
            ResultSetMetaData rsMd =rs.getMetaData();
            int cantidadColumnas=rsMd.getColumnCount();
            for (int i=1; i<=cantidadColumnas; i ++){
                model.addColumn(rsMd.getColumnLabel(i));
                
            }
            while(rs.next()){
                Object[] fila = new Object[cantidadColumnas];
                for (int j=1; j <= cantidadColumnas; j++){
                    fila[j-1]= rs.getObject(j);
                }
                model.addRow(fila);
                }
            }catch (Exception e){
                e.printStackTrace();
            }
    }//GEN-LAST:event_txtBuscarKeyReleased
public void limpiar(){
    txtid.setText("");
    txtNombre.setText("");
    txtApellidoP.setText("");
    txtApellidoM.setText("");
    txtEmail.setText("");
    txtUcuario.setText("");
    txtPassword.setText("");
    modificando=false;
    
}
    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCatalogoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCatalogoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCatalogoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCatalogoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCatalogoUsuario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableUsuario;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUcuario;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
