/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package usuarios;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author corona
 */
public class frmProducto extends javax.swing.JFrame {

    private Connection conexion;
    boolean modificando = false;
    

    /**
     * Creates new form frmProducto
     */
    public frmProducto() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        inicializaBaseDeDatos();
        llenartablaprecio();
    }

    public void inicializaBaseDeDatos() {
        try {
            DriverManager.registerDriver(new com.mysql.jdbc.Driver()); // para cargar el driver en java
            conexion = DriverManager.getConnection("jdbc:mysql://" + "localhost/punto_venta", "root", "");// PARA CONECTARNOS CON LA BASE DE DATOS
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
    }

    public void llenartablaprecio() {
        try {
            DefaultTableModel model = new DefaultTableModel();
            tableProducto.setModel(model);
            PreparedStatement consulta = conexion.prepareStatement("" + "SELECT * FROM producto Where status=1");
            ResultSet rs = consulta.executeQuery();
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
            for (int i = 1; i <= cantidadColumnas; i++) {
                model.addColumn(rsMd.getColumnLabel(i));
                
            }
            while (rs.next()) {
                Object[] fila = new Object[cantidadColumnas];
                for (int j = 1; j <= cantidadColumnas; j++) {
                    fila[j - 1] = rs.getObject(j);
                }
                model.addRow(fila);
            }
        } catch (Exception e) {
            e.printStackTrace();
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtExistencia = new javax.swing.JTextField();
        brnGuardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableProducto = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 34, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descripcion");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 79, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Precio");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 116, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Existencia");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 154, -1, -1));

        txtDescripcion.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 100, -1));

        txtPrecio.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 100, -1));

        txtExistencia.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        txtExistencia.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtExistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 100, -1));

        brnGuardar.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        brnGuardar.setForeground(new java.awt.Color(0, 0, 255));
        brnGuardar.setText("Guardar");
        brnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(brnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 40, -1, -1));

        tableProducto.setForeground(new java.awt.Color(0, 0, 255));
        tableProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableProducto);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 550, 130));

        btnModificar.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(0, 0, 255));
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 40, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID producto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 43, -1, -1));

        txtIdProducto.setEditable(false);
        txtIdProducto.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        txtIdProducto.setForeground(new java.awt.Color(51, 51, 51));
        txtIdProducto.setText("         Nuevo");
        getContentPane().add(txtIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 100, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Registro del Menu");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/menus.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 300, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondocafe.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int id = (int) tableProducto.getValueAt(tableProducto.getSelectedRow(), 0);
        String descripcion = (String) tableProducto.getValueAt(tableProducto.getSelectedRow(), 1);
        int precio = (int) tableProducto.getValueAt(tableProducto.getSelectedRow(), 2);
        String existencia = (String) tableProducto.getValueAt(tableProducto.getSelectedRow(), 3);
        
        txtIdProducto.setText("" + id);
        txtDescripcion.setText(descripcion);
        txtExistencia.setText(existencia);
        txtPrecio.setText("" + precio);
        brnGuardar.setText("Actualizar");
        modificando = true;
    }//GEN-LAST:event_btnModificarActionPerformed

    private void brnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnGuardarActionPerformed
        
        String descripcion = txtDescripcion.getText();
        String precio = txtPrecio.getText();
        String existencia = txtExistencia.getText();
       
        int id = 0;
        if (modificando) {
            id = Integer.parseInt(txtIdProducto.getText());
        }
        
        if (descripcion.length() == 0 || precio.length() == 0 || existencia.length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos para registrar");
            return;
        }
        try {
            PreparedStatement consulta;
            if (modificando) {
                consulta = conexion.prepareStatement("" + "UPDATE producto SET descripcion=?,precio=?,existencia=? WHERE id_producto=?");                
                consulta.setString(1, descripcion);
                consulta.setString(2,precio);
                consulta.setString(3, existencia);
                consulta.setInt(4, id);
            } else {
                consulta = conexion.prepareStatement("" + "INSERT INTO producto (descripcion,precio,existencia)VALUES(?,?,?)");
                consulta.setString(1, descripcion);
                consulta.setString(2, precio);
                consulta.setString(3, existencia);
            }
            consulta.executeUpdate();
            limpiar();
            llenartablaprecio();
            brnGuardar.setText("Guardar");
            txtIdProducto.setText("  Nuevo");
            
        } catch (SQLException ex) {
            ex.printStackTrace();
            
        }

    }//GEN-LAST:event_brnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int id = (int) tableProducto.getValueAt(tableProducto.getSelectedRow(), 0);
        try {
            PreparedStatement consulta = conexion.prepareStatement("" + "UPDATE  producto SET status=2 WHERE id_producto=?");
            consulta.setInt(1, id);
            consulta.executeUpdate();
            llenartablaprecio();
            limpiar();
            txtIdProducto.setText("   Nuevo");
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
    public void limpiar() {
        txtIdProducto.setText("");
        txtDescripcion.setText("");
        txtExistencia.setText("");
        txtPrecio.setText("");
        modificando = false;
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnGuardar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tableProducto;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtExistencia;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
